.ORIG x3000		; Start your program here

LDI R1,X		; R1 WILL CONTAIN THE VALUE OF THE NUMBER TO BE SHIFTED
LDI R2,N		; N IS HOW MUCH TO SHIFT BY
LDI R7,X		; R7 IS WHERE THE RESULT WILL BE STORED(WE NEED TO STAT IT WITH THE ORIGINAL VALUE IN CASE N IS ZERO)
LD R5,FIRSTBIT		; USED TO ANALYZE THE FIRST BIT OF THE LEFT SHIFT
LD R6,REDUCER		;THIS IS THE REUCER OF N AS ALL THE RELEVANT BITS ARE THE LAST 4


AND R2,R2,R6		; THIS REDUCES THE 16 MULTIPLES OF THE N AND MAKES ONLY THE LAST 4 BITS RELEVANT FOR MORE INFO LOOK IN THE DATA


ADD R2,R2,#0		;REINITIALIZE R2 TO CHEK IF N IS ZERO	
BRZ END			;IF IT IS ENDING THE PROGRAM

AND R7,R7,#0		; CLEARING R7 SO THAT IT NO LONGER HAS THE VLAUE OF X
AND R0,R0,#0		;CLEARING R0 JUST IN CASE


LOOP AND R0,R1,R5	; CONSIDERING THE FIRST BIT R1(THE LEFT SHIFTED VALUES) AND STORING IN R0 FORE MORE INFO ON HOW THIS IS DONE LOOK IN THE DATA
ADD R1,R1,R1		; LEFT SHIFTING
ADD R0,R0,#0		;RELOADING R0 FOR THE NEXT BRANCH
BRZ SKIP		; THIS IS AS THE THE FIRST BIT CAN EITHER BE 1 OR ZERO SO THE VALUE IS EITHER NEGATIVE OR ZERO. s FOR MORE INFO LOOK IN THE DATA
ADD R1,R1,#1		; ADD 1 TO R4 IN CASE THE FISRT BIT OF R4 BEFORE SHIFT WAS 1. iF IT WAS ZERO THIS STEP WILL BE SKIPPED AND ZERO WILL BE ADDED IN THE BACK BY DEFAULT
SKIP ADD R2,R2,#-1	; DOING N-1
BRP LOOP		;UNTIL N=0

ADD R7,R1,#0		; STORING THE SHIFTED VALUE R1 IN R7

END STI R7,RESULT	; STORING THE RESULT 



HALT			;End your program here

			
X 	 .FILL x4000
N 	 .FILL x4001
RESULT 	 .FILL x4002
REDUCER  .FILL x000F	;The first 3 BYTES OF THE N WILL NOT MATTER IN THE ROTATION AS THEY WILL RETURN THE SAME NUMBER. THIS IS AS THE FIRST 3 BYTES WILL BE THE FIRST 12 BITS AND ALL OF THEM WILL BE A MULTIPLE OF 16. IF THE ROTATION NUMBER IS A FACTOR OF 16 IT WILL RETURN THE SAME NUMBER THEREFORE WE CAN GET RID OF THEM AND CONSIDE ONLY THE LAST 4 BITS.
FIRSTBIT .FILL X8000	;THIS WILL BE USED TO CONSIDER THE FIRST BIT OF THE LEFT SHIFT. THIS IS AS X8000 IS 1000000000000000. wHEN WE AND THIS WITH ANY NUMBER WE WILL BE CONSIDERING THE FIRST BIT OF THE NUMBER. IF THE FIST BIT WAS 1 WE WILL HAVE A NEGATIVE NUMBER BUT IF THE FIRST BIT WAS ZERO WE CAN KNOW THAT THE RESULT OF IT WILL BE ZERO. WE WILL USE THIS FACT IN THE BRANCH STATEMENT.


.END
