// main.c
// Created By: Vickie Fridge
// Date Modified: April 4, 2017

// DO NOT EDIT THIS FILE 
// (Unless you already solved this exam and you're just curious)

#include <stdint.h>
#include "UART.h"
#include "Exam2.h"

#define strTests 7
#define lenTests 6

// Assembly Prototypes
int strLen (char* string);
int Check(char* str1, char* str2);

/*************** strCompare *************** 
 * Determines if two char strings are the same
 * Used to grade testcase 2 and testcase 3
 * INPUT: two char strings
 * OUTPUT: 1 if strings are equal
 * 				 0 if strings are not equal */
int strCompare(char str1[], char str2[]){
		int len1 = strLen(str1);
		int len2 = strLen(str2);
		int equal = 0; int i;
		if(len1 == len2){
				for(equal = 1, i = 0; i < len1; i++){
						if(str1[i] != str2[i]){
								equal = 0;
						}
				}
		}
		return equal;
}

/*************** yes *************** 
 * Prints yes to UART1 and updates score
 * INPUT: old score
 * OUTPUT: new score */
int yes(int score){
		UART_OutString("Yes!");
		UART_OutString(" Score = ");
		score += 5;
		UART_OutUDec(score);
		UART_OutCRLF();
		return score;
}

/*************** no *************** 
 * Prints your try, no, and score to UART1
 * INPUT: score and your data
 * OUTPUT: void */
void no(int score, int data){
		UART_OutString("Your = ");
		UART_OutUDec(data);
		UART_OutString(", No try again,");
		UART_OutString(" Score = ");
		UART_OutUDec(score);
		UART_OutCRLF();
}

//////////////////// MAIN FUNCTION //////////////////////
int main(void){
		UART_Init();       	//initialize UART
		UART_OutCRLF();
		UART_OutString("Exam2 Practice Test 1!\n\n\r");
	
		int score = 0;
		char* lenStrings[lenTests] = {"", "hi!", "@!#$%^&*()", "trick 0 you", "funny/b/b  /n",
																  "This is a long string of words to test your strLen function :)"};
		int lengths[lenTests] = {0, 3, 10, 11, 13, 62};
		Sentence para[strTests] = {{{"Alice was not here."}, {"not "}, -1},
															{{"Winter Summer is coming."}, {"Winter "}, -1},
															{{"Oatmeal raisin cookies are the bestest."}, {"est."}, -1},
															{{"Vvickie ivs mvakinvg mvore vvvtest cvvasvvesv..v."}, {"v"}, -1},
															{{"Puppies"}, {""}, -1},
															{{""}, {"a"}, -1},
															{{"SOSOk SO SOSthiSOSs iS SOSthe laSOst oneS0S!SOS"}, {"SOS"}, -1}}; 
		char* correctstr[strTests] = {"Alice was here.",
																	"Summer is coming.",
																	"Oatmeal raisin cookies are the best",
																	"Vickie is making more test cases...",
																	"Puppies",
																	"",
																	"Ok SO this iS the laSOst oneS0S!"};
		int correctedits[strTests] = {1, 1, 1, 14, 0, 0, 5};
		char* strings1[strTests] = {"",
																"The University of Texas at Austin",
																"123456789",
																"this is same",
																"what if there is no space",
																"how about a space at the end",
																"!@#$%^ ^ &*()__--"};
		char* strings2[strTests] = {"",
																"The University of Texas at Austin",
																"123456789",
																"this is not same",
																"whatifthereisnospace",
																"how about a space at the end ",
																"!@#$%^ ^ &*()__--"};	

		UART_OutString("Test of strLen \n");
		for(int i = 0; i<lenTests; i++){
				if(strLen(lenStrings[i]) == lengths[i]){
						score = yes(score); 
				}
				else{
						no(score, strLen(lenStrings[i]));
				}
		}
		
		UART_OutCRLF();
		UART_OutString("Test of fix \n");
		for(int i = 0; i<strTests; i++){
				fix(&para[i]);
				if((strCompare(para[i].words, correctstr[i]))&&(para[i].num_removed==correctedits[i])){
						score = yes(score);
			  }
				else{
						/* If you want more print statements
						UART_OutString("Sentence: ");
						UART_OutString(para[i].words);
						UART_OutCRLF();										
						UART_OutString("Remove: ");
						UART_OutString(para[i].remove);
						UART_OutCRLF();
						UART_OutString("Correct: ");
						UART_OutString(correctstr[i]);
						UART_OutCRLF();
						*/
						no(score, para[i].num_removed);
				}
		} 
		
		UART_OutCRLF();
		UART_OutString("Test of Check \n");
		for(int i = 0; i<strTests; i++){
				if(strCompare(strings1[i], strings2[i]) == Check(strings1[i], strings2[i])){
						score = yes(score);
				}
				else{
						no(score, Check(strings1[i], strings2[i]));
				}
		}
		
		UART_OutCRLF();
		UART_OutString("Final Score = ");
		UART_OutUDec(score);
		UART_OutCRLF();
		UART_OutString("------End of Test Cases------ ");											
												
		while(1){}
}

