// main.c
// Created By: Vickie Fridge and Thomas McRoberts
// Date Modified: April 3, 2017 

// DO NOT EDIT THIS FILE (unless you already solved this project and you're just curious)

#include <stdint.h>
#include <stdio.h>
#include "UART.h"

int Average(int* array);

int grader(int* arr){
		int size = arr[0];
		int sum = 0;
		for(int i = 1; i <= size; i++){
				sum += arr[i];
		}
		return sum/size;
}

int main(void){
		UART_Init();              // initialize UART
		UART_OutCRLF();
		UART_OutString("Debugging Example!\n\r");
		UART_OutCRLF();
	
		int arr[] = {4, 20, 15, 16, 19}; //actually is 17.5
																		 //should result as 17
		if(arr[0] > 0){
				UART_OutString("Test 1: ");
				for(int i = 1; i <= arr[0]; i++){
						UART_OutUDec(arr[i]);
						UART_OutString(", ");
				}
				UART_OutString("\b\b  \n\r");
				
				int avg = Average(arr);
				int correct = grader(arr);
				
				if(avg == correct){
						UART_OutString("YAY YOU DID IT!");
						UART_OutCRLF();
						UART_OutString("Average = ");
						UART_OutUDec(avg);
						UART_OutCRLF();
						UART_OutCRLF();
				} 
				else{
						UART_OutString("Sorry no...");
						UART_OutCRLF();
						UART_OutString("Your average = ");
						UART_OutUDec(avg);
						UART_OutCRLF();
						UART_OutString("Correct answer = ");
						UART_OutUDec(correct);
						UART_OutCRLF();
						UART_OutCRLF();
				}  
		}
		else UART_OutString("ERROR: no input numbers given\n\r");
		
		int arr2[] = {1, 5}; //should be 5
		if(arr2[0] > 0){
				UART_OutString("Test 2: ");
				for(int i = 1; i <= arr2[0]; i++){
						UART_OutUDec(arr2[i]);
						UART_OutString(", ");
				}
				UART_OutString("\b\b  \n\r");
				
				
				int avg = Average(arr2);
				int correct = grader(arr2);
				
				if(avg == correct){
						UART_OutString("YAY YOU DID IT!");
						UART_OutCRLF();
						UART_OutString("Average = ");
						UART_OutUDec(avg);
						UART_OutCRLF();
						UART_OutCRLF();
				} 
				else{
						UART_OutString("Sorry no...");
						UART_OutCRLF();
						UART_OutString("Your average = ");
						UART_OutUDec(avg);
						UART_OutCRLF();
						UART_OutString("Correct answer = ");
						UART_OutUDec(correct);
						UART_OutCRLF();
						UART_OutCRLF();
				}  
		}
		else UART_OutString("ERROR: no input numbers given\n\r");
		
		int arr3[] = {4, 0, 0, 81, 0}; //actually is 20.25
																		 //should result as 20
		if(arr3[0] > 0){
				UART_OutString("Test 3: ");
				for(int i = 1; i <= arr3[0]; i++){
						UART_OutUDec(arr3[i]);
						UART_OutString(", ");
				}
				UART_OutString("\b\b  \n\r");
				
				
				int avg = Average(arr3);
				int correct = grader(arr3);
				
				if(avg == correct){
						UART_OutString("YAY YOU DID IT!");
						UART_OutCRLF();
						UART_OutString("Average = ");
						UART_OutUDec(avg);
						UART_OutCRLF();
						UART_OutCRLF();
				} 
				else{
						UART_OutString("Sorry no...");
						UART_OutCRLF();
						UART_OutString("Your average = ");
						UART_OutUDec(avg);
						UART_OutCRLF();
						UART_OutString("Correct answer = ");
						UART_OutUDec(correct);
						UART_OutCRLF();
						UART_OutCRLF();
				}  
		}
		else UART_OutString("ERROR: no input numbers given\n\r");
		UART_OutString("------End of Test Cases------ ");	
		while(1){}
}
